version: "3"
services:
  nestjs_api:
    build:
      dockerfile: Dockerfile
      context: Backend
      target: development
    volumes:
      - ./Backend:/usr/src/app
    env_file:
      - ./Backend/.env
    command: npm run start:dev
    ports:
      - 8000:8000
    networks:
      - travel-network

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    networks:
      - travel-network


networks:
  travel-network:

